sudo: required

language: generic

services:
- docker

env:
- DISTRO=arch
- DISTRO=xenial
- DISTRO=artful

install:
- docker build . -t "$DISTRO" -f "dockerfiles/$DISTRO"

script:
- docker run -t "$DISTRO" make test
